version: "3"
services:
    web:
        build: .
        ports:
            - "8080:8080"
        environment: 
            - SECRET=86063018657Satala12#
    mongo:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        volumes:
            - "mongodb_data_container:/data/db"
volumes:
    mongodb_data_container: